/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pocky_libs_Pocky */

#ifndef _Included_pocky_libs_Pocky
#define _Included_pocky_libs_Pocky
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pocky_libs_Pocky
 * Method:    startup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pocky_libs_Pocky_startup
  (JNIEnv *, jclass);

/*
 * Class:     pocky_libs_Pocky
 * Method:    shutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pocky_libs_Pocky_shutdown
  (JNIEnv *, jclass);

/*
 * Class:     pocky_libs_Pocky
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_pocky_libs_Pocky_resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     pocky_libs_Pocky
 * Method:    draw
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_pocky_libs_Pocky_draw
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
