/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pineapple_libs_PineappleLib */

#ifndef _Included_pineapple_libs_PineappleLib
#define _Included_pineapple_libs_PineappleLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pineapple_libs_PineappleLib
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pineapple_libs_PineappleLib_test
  (JNIEnv *, jclass);

/*
 * Class:     pineapple_libs_PineappleLib
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pineapple_libs_PineappleLib_init
  (JNIEnv *, jclass);

/*
 * Class:     pineapple_libs_PineappleLib
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pineapple_libs_PineappleLib_start
  (JNIEnv *, jclass);

/*
 * Class:     pineapple_libs_PineappleLib
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pineapple_libs_PineappleLib_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
