/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pineapple_libs_GraphicsLib */

#ifndef _Included_pineapple_libs_GraphicsLib
#define _Included_pineapple_libs_GraphicsLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pineapple_libs_GraphicsLib
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pineapple_libs_GraphicsLib_init
  (JNIEnv *, jclass);

/*
 * Class:     pineapple_libs_GraphicsLib
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pineapple_libs_GraphicsLib_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
